[repo] reworks bin/init and bin/clean-* scripts

diff --git a/bin/init b/bin/init
--- a/bin/init
+++ b/bin/init
@@ -1,49 +1,152 @@
 #!/usr/bin/env sh
 
-################################################################################
-# USAGE
-# init
+# USAGE ########################################################################
+# [INIT_QUIET=true|false] init
 ################################################################################
 
 set -e
 set -u
 
 case $(dirname "$0") in
-    /*|./*) Dir=$(cd "$(dirname "$0")" && pwd);;
-    *) Dir=$(cd "$PWD/$(dirname "$0")" && pwd);;
+  /*|./*) Dir=$(cd "$(dirname "$0")" && pwd);;
+  *) Dir=$(cd "$PWD/$(dirname "$0")" && pwd);;
 esac
 
-error_message='\e[0;38;5;9mfailed\e[0m'
+repo_dir=$(cd "$Dir/.." && pwd)
 
-echo '┌─ Checking PNPM'
-if ! command -v pnpm >/dev/null 2>&1; then
-    echo "│ \"pnpm\" command not found."
-    printf "└─ $error_message\n"
-    exit 1
+: ${INIT_QUIET:=false}
+
+is_true() {
+  test $1 = true \
+    -o $1 = yes \
+    -o $1 = on \
+    -o $1 = 1 \
+  ;
+}
+
+is_false() {
+  test $1 = false \
+    -o $1 = no \
+    -o $1 = off \
+    -o $1 = 0 \
+  ;
+}
+
+match_semantic_version() {
+  grep --only-matching --extended-regexp --regexp '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1
+}
+
+get_version_major() {
+  printf '%s' "$1" | cut -d . -f 1 | grep --only-matching --extended-regexp --regexp '[0-9]+' || true
+}
+get_version_minor() {
+  printf '%s' "$1" | cut -d . -f 2 | grep --only-matching --extended-regexp --regexp '[0-9]+' || true
+}
+
+failure_message=' error '
+success_marker='\e[0;1;38;5;47m✓\e[0m'
+failure_marker="\e[0;1;48;5;124;38;5;9m${failure_message}\e[0m"
+
+args_quiet=false
+if is_true $INIT_QUIET; then
+  args_quiet=true
 fi
-pnpm_version=$(pnpm -v)
-pnpm_version_major=$(printf '%s' "$pnpm_version" | cut -d . -f 1 | { grep -o -E '[0-9]+' || true; })
-pnpm_version_minor=$(printf '%s' "$pnpm_version" | cut -d . -f 2 | { grep -o -E '[0-9]+' || true; })
+
+if is_true $args_quiet; then
+  exec 1>/dev/null # Redirects standard output to nowhere.
+fi
+
+printf '╭─ initializing workspace\n'
+printf '│\n'
+
+printf '├─[1/3] checking NodeJS\n'
+printf '│\n'
+if ! command -v node 1>/dev/null 2>&1; then
+  printf '╰─ ✕ failed\n'
+  printf 1>&2 "$failure_marker command \"node\" not found\n"
+  printf 1>&2 '\n'
+  printf 1>&2 'Please install NodeJS.\n'
+  exit 1
+fi
+node_version=$(node --version | sed -e 's/^v//' | match_semantic_version)
+node_version_major=$(get_version_major "$node_version")
+node_version_minor=$(get_version_minor "$node_version")
+if test -z "$node_version_major" -o -z "$node_version_minor"; then
+  printf '╰─ ✕ failed\n'
+  printf 1>&2 "$failure_marker unrecognized version format \"%s\"\n" "$node_version"
+  exit 1
+fi
+if \
+  test "$node_version_major" -lt 22 \
+  || test "$node_version_major" -eq 22 -a "$node_version_minor" -lt 3 \
+; then
+  printf '╰─ ✕ failed\n'
+  printf 1>&2 "$failure_marker legacy nodejs version\n"
+  printf 1>&2 'version: %s\n' "$node_version"
+  printf 1>&2 'path: %s\n' "$(which node)"
+  printf 1>&2 '\n'
+  printf 1>&2 'Legacy NodeJS versions are not supported.\n'
+  printf 1>&2 'Please upgrade to a version >= 22.3.\n'
+  exit 1
+fi
+printf '│ found version %s\n' "$node_version"
+printf "│ $success_marker ok\n"
+printf '│\n'
+
+printf '├─[2/3] checking PNPM\n'
+printf '│\n'
+if ! command -v pnpm 1>/dev/null 2>&1; then
+  printf '╰─ ✕ failed\n'
+  printf 1>&2 "$failure_marker command \"pnpm\" not found\n"
+  printf 1>&2 '\n'
+  printf 1>&2 'Please install PNPM.\n'
+  printf 1>&2 '$ npm install --global pnpm\n'
+  exit 1
+fi
+pnpm_version=$(pnpm --version | match_semantic_version)
+pnpm_version_major=$(get_version_major "$pnpm_version")
+pnpm_version_minor=$(get_version_minor "$pnpm_version")
 if test -z "$pnpm_version_major" -o -z "$pnpm_version_minor"; then
-    echo "│ unrecognized version format \"$pnpm_version\""
-    printf "└─ $error_message\n"
-    exit 2
+  printf '╰─ ✕ failed\n'
+  printf 1>&2 "$failure_marker unrecognized pnpm version\n"
+  printf 1>&2 'version: %s\n' "$pnpm_version"
+  printf 1>&2 '\n'
+  printf 1>&2 'Please install a recent PNPM version.\n'
+  printf 1>&2 '$ npm install --global pnpm\n'
+  exit 1
 fi
-if test "$pnpm_version_major" -lt 10 -o "$pnpm_version_minor" -lt 12; then
-    echo "│ found legacy version \"$pnpm_version\""
-    echo '│ please upgrade PNPM to version >= 10.12'
-    printf "└─ $error_message\n"
-    exit 3
+if \
+  test "$pnpm_version_major" -lt 10 \
+  || test "$pnpm_version_major" -eq 10 -a "$pnpm_version_minor" -lt 12 \
+; then
+  printf '╰─ ✕ failed\n'
+  printf 1>&2 "$failure_marker legacy pnpm version\n"
+  printf 1>&2 'version: %s\n' "$pnpm_version"
+  printf 1>&2 'path: %s\n' "$(which pnpm)"
+  printf 1>&2 '\n'
+  printf 1>&2 'Legacy PNPM versions are not supported.\n'
+  printf 1>&2 'Please upgrade to a version >= 10.12.\n'
+  printf 1>&2 '$ npm install --global pnpm\n'
+  exit 1
 fi
-echo "│ found version \"$pnpm_version\""
-echo '└─ done'
-echo
+printf '│ found version %s\n' "$pnpm_version"
+printf "│ $success_marker ok\n"
+printf '│\n'
 
-echo '┌─ Installing dependencies'
-{
-    if ! pnpm --dir "$Dir/../" run init 2>&1; then
-        printf "$error_message\n"
-        exit 4
-    fi
-} | sed -e 's/^/│ /'
-echo '└─ done'
+printf '├─[3/3] installing dependencies\n'
+printf '│\n'
+set +e
+command_output=$(cd "$repo_dir/" && node --run init 2>&1)
+command_exit=$?
+set -e
+printf '%s\n' "$command_output" | sed -e 's/^/│ /'
+if test $command_exit -ne 0; then
+  printf '╰─ ✕ failed\n'
+  printf 1>&2 "$failure_marker installation failed\n"
+  printf 1>&2 '%s\n' "$command_output"
+  exit 1
+fi
+printf "│ $success_marker ok\n"
+printf '│\n'
+
+printf "╰─ $success_marker done\n"
